const model = require('./models/models');
const swaggerAutogen = require('swagger-autogen')();

const outputFile = './src/swagger/swagger_output.json'
const endpointsFiles = [
    './src/api/customers/customer.controller',
    './src/api/localizations/localization.controller',
    './src/shared/custom-error',
]

const doc = {
    info: {
        version: "1.0.0",
        title: "Customer Manager API",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/api/v1/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        Customers: model.customersResponse,
        CustomersList: model.customersListResponse,
        Localizations: model.localizationsResponse,
        Cities: model.citiesResponse,
        CustomError: model.customError
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc);